#!/usr/bin/env node

import { existsSync, readFileSync, writeFileSync } from "fs";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";
import type { Model } from "../src/types.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, "..");
const PROVIDER_ID = "kimi-coding";

export const KIMI_CODING_COMPATIBILITY_MODELS = {
	"kimi-for-coding": {
		id: "kimi-for-coding",
		name: "Kimi For Coding",
		api: "anthropic-messages",
		provider: PROVIDER_ID,
		baseUrl: "https://api.kimi.com/coding",
		headers: { "User-Agent": "KimiCLI/1.5" },
		compat: { allowEmptySignature: true, forceAdaptiveThinking: true },
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.95, output: 4, cacheRead: 0.19, cacheWrite: 0 },
		contextWindow: 262144,
		maxTokens: 32768,
	},
	"kimi-k2-thinking": {
		id: "kimi-k2-thinking",
		name: "Kimi K2 Thinking",
		api: "anthropic-messages",
		provider: PROVIDER_ID,
		baseUrl: "https://api.kimi.com/coding",
		headers: { "User-Agent": "KimiCLI/1.5" },
		compat: { forceAdaptiveThinking: true },
		reasoning: true,
		input: ["text"],
		cost: { input: 0.6, output: 2.5, cacheRead: 0.15, cacheWrite: 0 },
		contextWindow: 262144,
		maxTokens: 32768,
	},
} satisfies Record<string, Model<"anthropic-messages">>;

export function ensureKimiCodingCompatibilityModels(
	models: Record<string, Model<any>>,
): Record<string, Model<any>> {
	const result = { ...models };
	for (const [modelId, model] of Object.entries(KIMI_CODING_COMPATIBILITY_MODELS)) {
		if (!result[modelId]) {
			result[modelId] = structuredClone(model);
		}
	}
	return Object.fromEntries(Object.entries(result).sort(([left], [right]) => left.localeCompare(right)));
}

function writeJson(path: string, value: unknown): void {
	writeFileSync(path, `${JSON.stringify(value)}\n`);
}

function renderStructuralCatalog(models: Record<string, Model<any>>): string {
	let output = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

`;
	output += `import values from "./data/${PROVIDER_ID}.json" with { type: "json" };\n`;
	output += `import type { Model } from "../types.ts";\n\n`;
	output += "export const KIMI_CODING_MODELS = values as {\n";
	for (const model of Object.values(models)) {
		output += `\t${JSON.stringify(model.id)}: Model<${JSON.stringify(model.api)}> & {\n`;
		output += `\t\tid: ${JSON.stringify(model.id)};\n`;
		output += `\t\tprovider: ${JSON.stringify(model.provider)};\n`;
		output += "\t};\n";
	}
	output += "};\n";
	return output;
}

function updateSourceCatalog(): Record<string, Model<any>> {
	const dataPath = join(packageRoot, "src/providers/data/kimi-coding.json");
	if (!existsSync(dataPath)) {
		throw new Error(`Generated Kimi catalog not found: ${dataPath}`);
	}
	const current = JSON.parse(readFileSync(dataPath, "utf8")) as Record<string, Model<any>>;
	const compatible = ensureKimiCodingCompatibilityModels(current);
	writeJson(dataPath, compatible);
	writeFileSync(join(packageRoot, "src/providers/kimi-coding.models.ts"), renderStructuralCatalog(compatible));
	return compatible;
}

function updateJsonCatalog(outputDir: string, compatible: Record<string, Model<any>>): void {
	const providersDir = join(outputDir, "providers");
	const providerPath = join(providersDir, "kimi-coding.json");
	const modelsPath = join(outputDir, "models.json");
	if (!existsSync(providerPath) || !existsSync(modelsPath)) {
		throw new Error(`Generated JSON catalog not found under: ${outputDir}`);
	}

	writeJson(providerPath, compatible);
	const models = JSON.parse(readFileSync(modelsPath, "utf8")) as Record<string, Record<string, Model<any>>>;
	models[PROVIDER_ID] = compatible;
	writeJson(modelsPath, Object.fromEntries(Object.entries(models).sort(([left], [right]) => left.localeCompare(right))));
}

function readJsonOutputDir(args: string[]): string | undefined {
	for (let index = 0; index < args.length; index++) {
		if (args[index] !== "--json-output") continue;
		const value = args[index + 1];
		if (!value) throw new Error("--json-output requires a directory");
		return resolve(value);
	}
	return undefined;
}

function main(): void {
	const compatible = updateSourceCatalog();
	const jsonOutputDir = readJsonOutputDir(process.argv.slice(2));
	if (jsonOutputDir) updateJsonCatalog(jsonOutputDir, compatible);
	console.log("Preserved stable Kimi Coding compatibility model IDs");
}

if (process.argv[1] && resolve(process.argv[1]) === __filename) {
	try {
		main();
	} catch (error) {
		console.error(error);
		process.exitCode = 1;
	}
}
